# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7274c3c74412ff78d71528a92954ef2ef37a90c72bfb6b9dd3b71ea50488c9245d34dab23e8591199c4a79adc5c9762608026b222e5014e122e5f78414b3d6ec

test:
  secret_key_base: d855e8c9c399a238e3fb1f137d00435fda158690ae1be0b87da1c2a1c5e5793128597932691d2f5b09fdf159b08c0b93e0f580957d2e064c1ae4b6b5aec8e305

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
